anyOf:
# The branch name must exactly match "master"...
- uses: exactly
  with:
    allowed: [master]
    
# ...or must contain an issue number followed by a kebab cased
# ticket title.
- uses: numbered
