name: Continuous Integration

env:
  NODE_VERSION: 16

on: [push, pull_request]

jobs:
  lint:
    runs-on: ubuntu-20.04

    steps:
    - name: Checkout the Repository
      uses: actions/checkout@v2
      
    - name: Use Node.js
      uses: actions/setup-node@v2
      with:
        node-version: ${{ env.NODE_VERSION }}
      
    - name: Install Dependencies
      run: |
        npm ci
      env:
        CI: true

    - name: Lint
      run: |
        npm run lint

  test:
    runs-on: ubuntu-20.04

    steps:
    - name: Checkout the Repository
      uses: actions/checkout@v2
      
    - name: Use Node.js
      uses: actions/setup-node@v2
      with:
        node-version: ${{ env.NODE_VERSION }}
      
    - name: Install Dependencies
      run: |
        npm ci
      env:
        CI: true

    - name: Run Tests
      run: |
        npm run test

    - name: Publish Unit Test Results
      uses: EnricoMi/publish-unit-test-result-action@v1
      if: always()
      with:
        files: junit.xml

  build:
    needs: [lint, test]

    runs-on: ubuntu-20.04

    steps:
    - name: Checkout the Repository
      uses: actions/checkout@v2
      
    - name: Use Node.js
      uses: actions/setup-node@v2
      with:
        node-version: ${{ env.NODE_VERSION }}
      
    - name: Install Dependencies
      run: |
        npm ci
      env:
        CI: true

    - name: Build
      run: |
        pnpm run compile
